### PR TITLE
Adding and Merging CLUE Repurposing Data

### PR DESCRIPTION
**Pull request by gwaygenomics**
As described in https://github.com/broadinstitute/lincs-cell-painting/issues/5#issuecomment-600208689, I add 

* The two CLUE data files
* A CLUE specific README
* An `md5sum` file to confirm future download integrity
* A notebook to reconcile and merge the two data types
* Two forms of the processed data

### CODE REVIEW

**Comment by gwaygenomics** [comment]
@niranjchandrasekaran @shntnu - I'll leave this PR open for a while, until we can finalize some remaining items (https://github.com/broadinstitute/lincs-cell-painting/issues/5#issuecomment-601917321). In the meantime, I think the logic and documentation here would benefit from your insight

**Comment by shntnu** [comment]
> I think the logic and documentation here would benefit from your insight

Sure

What should I review – your notes in #5 or the files in the PR?

**Comment by gwaygenomics** [comment]
This PR please :D

**Comment by shntnu** [comment]
The logic looks good. I did a basic check.

```r
x <- repurposing_info %>% distinct(broad_id, moa) %>% na.omit %>% mutate(n = 1 + str_count(moa, "\\|")) %>% select(-moa) %>% arrange(broad_id)
y <- repurposing_info_long %>% distinct(broad_id, moa_unique) %>% na.omit %>% count(broad_id) %>% arrange(broad_id)
inner_join(x, y, by = c("broad_id")) %>% filter(n.x != n.y) %>% count()
> # A tibble: 1 x 1
>       n
>   <int>
> 1     0
```

**Comment by shntnu** [comment]
The README is good too 👍

**Comment by shntnu** [comment]
You can go ahead and do what's discussed in https://github.com/broadinstitute/lincs-cell-painting/issues/5#issuecomment-601917321

**Comment by gwaygenomics** [comment]
most recent set of commits occur after incorporating updated data in https://github.com/broadinstitute/lincs-cell-painting/issues/8#issuecomment-603314909

**Comment by gwaygenomics** [comment]
@shntnu @niranjchandrasekaran - I think this PR is ready to merge. Please let me know if there's anything else you think belongs here

**Comment by shntnu** [comment]
Cool! I can't think of anything else right now.

**Comment by gwaygenomics** [comment]
great! I will merge

**Pull request merged**
