### PR TITLE
Create manifest file for clue.io

### PR DESCRIPTION
**Pull request by shntnu**
We will run the notebook in this PR once the profiles are available in the repo. The files also need to be checkedout locally to calculate file sizes and md5.

@gwaygenomics FYI

### CODE REVIEW

**Comment by gwaygenomics** [comment]
After merging #34 and #36 I think we can wrap this PR up - @shntnu is there anything I can do?

**Comment by shntnu** [comment]
Quick notes

- size and sha can be gotten like this

```r
read_lines("https://raw.githubusercontent.com/broadinstitute/lincs-cell-painting/master/profiles/2016_04_01_a549_48hr_batch1/SQ00015041/SQ00015041_normalized.csv.gz")[[2]] %>% str_remove("oid sha256:")
```

```
> [1] "211cfedea2ad539a722224f741e5e1c32d5ec022074476d7b54d19ce33ffd50e"
```

```r
read_lines("https://raw.githubusercontent.com/broadinstitute/lincs-cell-painting/master/profiles/2016_04_01_a549_48hr_batch1/SQ00015041/SQ00015041_normalized.csv.gz")[[3]] %>% str_remove("size ")
```

```
> [1] "2102378"
```

**Comment by shntnu** [comment]
The manifest file in 3d23339 is a good first version; we can iterate with feedback from CMap later.

- Level 5 data is not present in this file 
- The notebook has no documentation 
- I am using SHA256 instead of MD5 because that was easily available via GitHub

I'd vote to go ahead and merge; I will fix all this in the next iteration.

**Comment by gwaygenomics** [comment]
from Jacob:

> We have a hard coded header on the page that says "MD5"., s o could you supply the MD5 hashes instead?

Looks like [`md5sum()`](https://www.rdocumentation.org/packages/tools/versions/3.6.2/topics/md5sum) is a thing

**Comment by gwaygenomics** [comment]
> Level 5 data is not present in this file
> The notebook has no documentation
> I am using SHA256 instead of MD5 because that was easily available via GitHub

I can do this second thing (as opposed to "first thing" 😄 ) this morning. Does that sound ok? If you think it'll be quicker to just do on your own, LMK

**Comment by shntnu** [comment]
- ~~Level 5 data is not present in this file~~ DONE
- ~~The notebook has no documentation~~ DONE
- I am using SHA256 instead of MD5 because that was easily available via GitHub --> the code for this in now in the notebook, but we'd need to rerun this notebook locally after merging with master so that the file sizes and md5 can be calculated. Can you do so @gwaygenomics ?

**Comment by gwaygenomics** [comment]
> I am using SHA256 instead of MD5 because that was easily available via GitHub --> the code for this in now in the notebook, but we'd need to rerun this notebook locally after merging with master so that the file sizes and md5 can be calculated. Can you do so @gwaygenomics ?

all set @shntnu 

Note the changes include:

- Adding a missing value check for `md5` and `size` columns
- Minor comment adjustments
- Switch from `master` to github hash for urls

Ready for another look 🚀

**Comment by shntnu** [comment]
> Ready for another look 🚀

You may choose to update https://github.com/shntnu/lincs-cell-painting/blob/clue-manifest/environment.yml. Not tested:

```yaml
- conda-forge::r-tidyverse=1.3.0
- conda-forge::r-knitr=1.28
- conda-forge::r-rCurl=1.98.1.1
```

Rest looks good to go!

**Comment by gwaygenomics** [comment]
I tried two things here, both have failed.

1. Running the conda environment inside RStudio. [This thread](https://community.rstudio.com/t/start-rstudio-server-session-in-conda-environment/12516) seems to indicate that this is not possible
2. Rendering the RMarkdown file in the command line after configuring the environment. This seems to work, except I cannot get it to play nicely with `RCurl::url.exists()`. I have tried a bunch of different things (including different versions of all of the packages and base R) now and this error persists:

```bash
Error in file(file, ifelse(append, "a", "w")) :
  cannot open the connection
Calls: <Anonymous> ... block_exec -> in_dir -> .handleSimpleError -> h -> cat -> file
In addition: Warning message:
In file(file, ifelse(append, "a", "w")) :
  cannot open file 'clue_data_library.knit.md': Too many open files
```

I think there is some sort of memory leak going on that is somehow handled by my base R installation outside of conda. I could not find many related issues online, and have yet to solve this.

Is there an alternative way to run `.Rmd` files? Note that this markdown file executes perfectly in RStudio.

**Comment by gwaygenomics** [comment]
Now trying to downgrade `pandoc`. I can knit in Rstudio just fine, but I can't render via command line. Maybe this is a pandoc version issue.

In the conda environment:

```R
> rmarkdown::pandoc_version()
[1] ‘2.9.2.1’
```

In Rstudio:

```R
> rmarkdown::pandoc_version()
[1] ‘2.3.1’
```

**Comment by gwaygenomics** [comment]
☝️ didn't work either. I also tried switching from `RCurl` to `httr` and using:

```R
check_file_exists <- function(url) {
  response <- httr::GET(url)
  if (response$status_code == 200) {
    exists <- TRUE
  } else {
    exists <- FALSE
  }
  return(exists)
}
```

This works both locally and with conda/command line (phew!)

**Comment by gwaygenomics** [comment]
ok @shntnu - ready for another look

**Comment by shntnu** [comment]
Wow that was rough! But really glad you could delve into it a bit. 

<details>
 <summary>Adding links below for ourselves.</summary>
- https://github.com/broadinstitute/2018_02_07_Image_based_Profiling_Pilot/issues/5 where we discusses `checkpoint` vs `conda-forge` (and decided to go with `checkpoint` at least when it is an R-only project
- https://github.com/broadinstitute/2018_02_07_Image_based_Profiling_Pilot/issues/28#issuecomment-499145184 where we were concerned that `checkpoint` wasn't behaving nicely
- where we wrote down instructions for installing R so that it `checkpoint` and other packages behave nicely _We found that a homebrew installation of R results in permission errors with `checkpoint` and library dependency errors with several packages. We didn't drill down to the source but we found that installing R 3.6.x from CRAN and then following these [instructions](https://thecoatlessprofessor.com/programming/cpp/r-compiler-tools-for-rcpp-on-macos/) ironed out all these issues. Be sure to `brew uninstall R` before installing from CRAN._
- https://github.com/broadinstitute/2018_02_07_Image_based_Profiling_Pilot/blob/master/install.R which is a script written by @gwaygenomics for setting up environment via `checkpoint`.
</details>

**Comment by shntnu** [comment]
I renamed `5a` to `5_median` and 5b to `5_modz`
`5a` and `5b` were inconsistent with the naming scheme because `5b` does not depend on `5a`, but our informal convention is that a dependency is implied (e.g. `4b` depends on `4a`). 

I didn't encode method tags in other levels e.g. `3_mean` or `4a_dmso_robustized` because we expect to settle on a single method for each level. `5` might be an exception so for now, I have encoded the method name for that.

Other than this, I think we are set.

**Comment by gwaygenomics** [comment]
@shntnu - I am going to produce consensus signatures using whole plate normalized profiles (per our conversation at checkin today). Should we add those to this manifest?

**Comment by shntnu** [comment]
> @shntnu - I am going to produce consensus signatures using whole plate normalized profiles (per our conversation at checkin today). Should we add those to this manifest?

In addition to DMSO normalized that is?

For my reference, currently it is DMSO normalized
https://github.com/shntnu/lincs-cell-painting/blob/99cbec7d6e01528dfea9a1d128806e6a5f5339fa/consensus/scripts/nbconverted/build-consensus-signatures.py#L60

**Comment by gwaygenomics** [comment]
updated commit hash after merging #41 and rerunning pipeline

**Comment by gwaygenomics** [comment]
I forgot to merge before rerunning 🤦  - I diagnosed this by looking at the diffs and noticing the md5s didn't change for the consensus signatures. The note "In addition to DMSO normalized that is?" prompted me to confirm.

Note the md5sums do change in fb87a3b32d6af83fe91622ef2069488f1488b894

**Comment by shntnu** [comment]
LGTM 💯 🥇

**Pull request merged**
