### PR TITLE
Adding missing platemap

### PR DESCRIPTION
**Pull request by gwaygenomics**
The platemap `C-7161-01-LM6-003.txt` was missing from the original platemap metadata upload in #10 

It is unclear why this platemap was missed. A couple of notes:

* The `metadata` folder is nearly empty in `~/efs/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/workspace/metadata`
* It is missing from the bucket folder

```bash
(base) ubuntu@ip-10-0-9-22:~/bucket/projects/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/workspace/metadata/2016_04_01_a549_48hr_batch1/platemap$ ls
barcode_platemap.csv   C-7161-01-LM6-007.txt  C-7161-01-LM6-013.txt  C-7161-01-LM6-019.txt  C-7161-01-LM6-025.txt
C-7161-01-LM6-001.txt  C-7161-01-LM6-008.txt  C-7161-01-LM6-014.txt  C-7161-01-LM6-020.txt  C-7161-01-LM6-026.txt
C-7161-01-LM6-002.txt  C-7161-01-LM6-009.txt  C-7161-01-LM6-015.txt  C-7161-01-LM6-021.txt  C-7161-01-LM6-027.txt
C-7161-01-LM6-004.txt  C-7161-01-LM6-010.txt  C-7161-01-LM6-016.txt  C-7161-01-LM6-022.txt  C-7161-01-LM6-028.txt
C-7161-01-LM6-005.txt  C-7161-01-LM6-011.txt  C-7161-01-LM6-017.txt  C-7161-01-LM6-023.txt
C-7161-01-LM6-006.txt  C-7161-01-LM6-012.txt  C-7161-01-LM6-018.txt  C-7161-01-LM6-024.txt
```

I don't know the last time I checked either resource, but I did notice that the code in #21 failed whenever it was processing a plate with the `C-7161-01-LM6-003.txt` platemap.

### CODE REVIEW

**Comment by gwaygenomics** [comment]
thanks for quick review 🚀 - I realized when I was about to merge that I need to rerun all the metatadata notebooks after adding the platemap. I will simply rerun all the scripts and add the changes here. It would be good to have another quick look before finally merging, since there will be a few updated (and important files) Sorry for the inconvenience!

## What changed in the mapping file:

image

image

Looking back, the number 1514 should have alerted my attention more. I am much more comfortable with the updated 1570!

Additional commits incoming

**Comment by gwaygenomics** [comment]
Note that the numbers in #20 are no longer accurate

**Comment by gwaygenomics** [comment]
alright @niranjchandrasekaran - PR ready for another quick look. Last time for this PR I swear!

**Comment by niranjchandrasekaran** [comment]
> Looking back, the number 1514 should have alerted my attention more. I am much more comfortable with the updated 1570!

@gwaygenomics Do we know what the actual number should be (the number of compounds that were profiled)? Is it 1570?

**Comment by gwaygenomics** [comment]
> @gwaygenomics Do we know what the actual number should be (the number of compounds that were profiled)? Is it 1570?

This is the number I have always seen historically. I do not know what it should be _officially_ (there is probably documentation somewhere...). I imagine that one way to get this official number is to look at all the platemaps, which are being added in this PR

**Comment by niranjchandrasekaran** [comment]
Sounds good. This PR is ready for merge.

**Comment by shntnu** [comment]
> This is the number I have always seen historically

Yep

2017-06-08 LINCS Cell Painting Pilot update

[Source](https://docs.google.com/presentation/d/1k_zj5wD1Jk9MqO7vJP6q_H6wbhTg3xNRazalflM7yEo/edit#slide=id.g1876cb98af_0_100)

Also confirmed by looking up metadata

```sh
cd ~/work/projects/2015_10_05_DrugRepurposing_AravindSubramanian_GolubLab_Broad/workspace/metadata/2016_04_01_a549_48hr_batch1_test/platemap
csvstack -t *.txt > /tmp/a
csvcut -c broad_sample /tmp/a|grep BRD|sort -u|wc -l
    1570
```

**Pull request merged**
