### PR TITLE
Updating Directory Structure of Metadata and Profiles

### LINKED ISSUE #23: Define folder structure
@gwaygenomics it might be useful to define the folder structure of the data

Here's what I am thinking https://github.com/cytomining/profiling-handbook/issues/54#issue-610880499 but feel free to propose alternatives. 

[This](https://cytomining.github.io/profiling-handbook/appendix-a.html#project-folder-structure-guidance) was our thinking when we defined the folder structure (transcribed by @gwaygenomics)

### PR DESCRIPTION
**Pull request by gwaygenomics**
closes #23

### CODE REVIEW

**Comment by shntnu** [comment]
Oh wait; that should be 

```
metadata/
├── 2016_04_01_a549_48hr_batch1
│   ├── barcode_platemap.csv
│   └── platemap
│       ├── C-7161-01-LM6-001.txt
│       ├── C-7161-01-LM6-002.txt
│       ├── C-7161-01-LM6-003.txt
```

The nesting you have is different

**Comment by shntnu** [comment]
I'll make another PR

**Comment by shntnu** [comment]
@gwaygenomics Can you go ahead and fix that; easier that way that my trying to move things around.

**Comment by gwaygenomics** [comment]
oh shoot - good catch. Yes, will do

**Pull request merged**
